/**
 * Icons an admin can pick for services and categories. The dashboard and the
 * marketing site ship identical copies of this file so every saved name
 * renders on both sides — keep them in sync.
 */

import {
    PaletteIcon,
    BrushIcon,
    PaintbrushIcon,
    PaintBucketIcon,
    PenToolIcon,
    PencilIcon,
    PenLineIcon,
    ShapesIcon,
    LayersIcon,
    Layers2Icon,
    FrameIcon,
    CropIcon,
    ScissorsIcon,
    PipetteIcon,
    EraserIcon,
    HighlighterIcon,
    ImageIcon,
    ImagesIcon,
    ImagePlusIcon,
    CameraIcon,
    ApertureIcon,
    WandIcon,
    WandSparklesIcon,
    SparklesIcon,
    SparkleIcon,
    StarIcon,
    GemIcon,
    CrownIcon,
    AwardIcon,
    TypeIcon,
    BaselineIcon,
    LetterTextIcon,
    SwatchBookIcon,
    ComponentIcon,
    Grid3x3Icon,
    LayoutGridIcon,
    LayoutTemplateIcon,
    LayoutDashboardIcon,
    LayoutListIcon,
    LayoutIcon,
    PanelTopIcon,
    RulerIcon,
    DraftingCompassIcon,
    SplineIcon,
    BlendIcon,
    ContrastIcon,
    DropletIcon,
    StampIcon,
    StickerIcon,
    BadgeCheckIcon,
    FeatherIcon,
    SignatureIcon,
    SquareIcon,
    CircleIcon,
    TriangleIcon,
    HexagonIcon,
    DiamondIcon,
    PentagonIcon,
    OctagonIcon,
    ShellIcon,
    FlowerIcon,
    Flower2Icon,
    RainbowIcon,
    CodeIcon,
    CodeXmlIcon,
    BracesIcon,
    BracketsIcon,
    TerminalIcon,
    SquareTerminalIcon,
    GlobeIcon,
    EarthIcon,
    MonitorIcon,
    MonitorSmartphoneIcon,
    LaptopIcon,
    SmartphoneIcon,
    TabletIcon,
    TabletSmartphoneIcon,
    AppWindowIcon,
    ServerIcon,
    DatabaseIcon,
    CloudIcon,
    CloudUploadIcon,
    CloudCogIcon,
    CpuIcon,
    HardDriveIcon,
    NetworkIcon,
    WifiIcon,
    LinkIcon,
    Link2Icon,
    PlugIcon,
    PuzzleIcon,
    BugIcon,
    GitBranchIcon,
    GitMergeIcon,
    GitPullRequestIcon,
    WebhookIcon,
    WorkflowIcon,
    BlocksIcon,
    BoxesIcon,
    SettingsIcon,
    Settings2Icon,
    WrenchIcon,
    HammerIcon,
    CogIcon,
    RocketIcon,
    ZapIcon,
    GaugeIcon,
    ShieldCheckIcon,
    ShieldIcon,
    LockIcon,
    KeyRoundIcon,
    FingerprintIcon,
    AccessibilityIcon,
    MousePointerIcon,
    MousePointerClickIcon,
    KeyboardIcon,
    FileCodeIcon,
    FileJsonIcon,
    ContainerIcon,
    BinaryIcon,
    BotIcon,
    BrainCircuitIcon,
    BrainIcon,
    CableIcon,
    RouterIcon,
    UnplugIcon,
    SatelliteIcon,
    RadioIcon,
    QrCodeIcon,
    ScanLineIcon,
    MicrochipIcon,
    VariableIcon,
    FunctionSquareIcon,
    SigmaIcon,
    ShoppingBagIcon,
    ShoppingCartIcon,
    ShoppingBasketIcon,
    StoreIcon,
    PackageIcon,
    PackageSearchIcon,
    PackageCheckIcon,
    PackageOpenIcon,
    PackagePlusIcon,
    TruckIcon,
    TagIcon,
    TagsIcon,
    TicketIcon,
    ReceiptIcon,
    ReceiptTextIcon,
    CreditCardIcon,
    WalletIcon,
    BanknoteIcon,
    CoinsIcon,
    DollarSignIcon,
    EuroIcon,
    PoundSterlingIcon,
    BadgePercentIcon,
    PercentIcon,
    GiftIcon,
    BarcodeIcon,
    ScanBarcodeIcon,
    WarehouseIcon,
    HandshakeIcon,
    HandCoinsIcon,
    PiggyBankIcon,
    CalculatorIcon,
    ScaleIcon,
    ForkliftIcon,
    PlaneIcon,
    ShipIcon,
    MapPinIcon,
    MapIcon,
    ShirtIcon,
    WatchIcon,
    GlassesIcon,
    FootprintsIcon,
    SofaIcon,
    LampIcon,
    ArmchairIcon,
    BedIcon,
    MegaphoneIcon,
    TrendingUpIcon,
    ChartLineIcon,
    ChartBarIcon,
    ChartPieIcon,
    ChartColumnIcon,
    ChartAreaIcon,
    ChartNoAxesCombinedIcon,
    ChartSplineIcon,
    PresentationIcon,
    TargetIcon,
    CrosshairIcon,
    SearchIcon,
    SearchCheckIcon,
    ScanSearchIcon,
    RadarIcon,
    RssIcon,
    MailIcon,
    MailOpenIcon,
    SendIcon,
    AtSignIcon,
    ShareIcon,
    Share2Icon,
    ThumbsUpIcon,
    HeartIcon,
    MessageCircleIcon,
    MessageSquareIcon,
    MessagesSquareIcon,
    BellIcon,
    BellRingIcon,
    SpeakerIcon,
    PodcastIcon,
    NewspaperIcon,
    HashIcon,
    FlameIcon,
    MagnetIcon,
    FunnelIcon,
    EyeIcon,
    LightbulbIcon,
    GoalIcon,
    TrophyIcon,
    MedalIcon,
    FlagIcon,
    MilestoneIcon,
    SignpostIcon,
    CompassIcon,
    NavigationIcon,
    ActivityIcon,
    MousePointer2Icon,
    SmileIcon,
    Users2Icon,
    UserSearchIcon,
    TelescopeIcon,
    BinocularsIcon,
    VideoIcon,
    FilmIcon,
    ClapperboardIcon,
    PlayIcon,
    CirclePlayIcon,
    MonitorPlayIcon,
    TvIcon,
    ProjectorIcon,
    FocusIcon,
    ScanIcon,
    Move3dIcon,
    Rotate3dIcon,
    BoxIcon,
    CylinderIcon,
    ConeIcon,
    PyramidIcon,
    TorusIcon,
    OrbitIcon,
    AtomIcon,
    Axis3dIcon,
    MusicIcon,
    Music2Icon,
    MicIcon,
    MicVocalIcon,
    HeadphonesIcon,
    AudioLinesIcon,
    AudioWaveformIcon,
    Volume2Icon,
    DiscIcon,
    Disc3Icon,
    DramaIcon,
    GhostIcon,
    Gamepad2Icon,
    JoystickIcon,
    PopcornIcon,
    SquarePlayIcon,
    TimerIcon,
    RepeatIcon,
    ShuffleIcon,
    FastForwardIcon,
    RewindIcon,
    SkipForwardIcon,
    WebcamIcon,
    CctvIcon,
    SwitchCameraIcon,
    ImagePlayIcon,
    SpotlightIcon,
    FileTextIcon,
    FileIcon,
    FilesIcon,
    FilePenIcon,
    FileCheckIcon,
    FileSearchIcon,
    BookIcon,
    BookOpenIcon,
    BookOpenTextIcon,
    LibraryIcon,
    NotebookIcon,
    NotebookPenIcon,
    NotepadTextIcon,
    ScrollTextIcon,
    ScrollIcon,
    QuoteIcon,
    SquarePenIcon,
    LanguagesIcon,
    TextIcon,
    HeadingIcon,
    ListIcon,
    ListChecksIcon,
    ListOrderedIcon,
    ClipboardListIcon,
    ClipboardCheckIcon,
    StickyNoteIcon,
    BookmarkIcon,
    ArchiveIcon,
    FolderOpenIcon,
    FolderIcon,
    PrinterIcon,
    MailsIcon,
    InboxIcon,
    BookMarkedIcon,
    BookTextIcon,
    CaptionsIcon,
    TabletsIcon,
    BriefcaseIcon,
    BriefcaseBusinessIcon,
    BuildingIcon,
    Building2Icon,
    LandmarkIcon,
    FactoryIcon,
    UsersIcon,
    UserIcon,
    UserCheckIcon,
    UserPlusIcon,
    UserCogIcon,
    UserRoundIcon,
    ContactIcon,
    IdCardIcon,
    HeartHandshakeIcon,
    LaughIcon,
    CalendarIcon,
    CalendarCheckIcon,
    CalendarDaysIcon,
    ClockIcon,
    HourglassIcon,
    AlarmClockIcon,
    HeadsetIcon,
    PhoneIcon,
    PhoneCallIcon,
    LifeBuoyIcon,
    CircleHelpIcon,
    InfoIcon,
    MessageCircleQuestionIcon,
    ShieldPlusIcon,
    GavelIcon,
    GraduationCapIcon,
    SchoolIcon,
    KanbanIcon,
    SquareKanbanIcon,
    ListTodoIcon,
    CheckCheckIcon,
    CircleCheckIcon,
    GroupIcon,
    WaypointsIcon,
    LeafIcon,
    SproutIcon,
    TreePineIcon,
    RecycleIcon,
    HouseIcon,
    HotelIcon,
    UtensilsIcon,
    CoffeeIcon,
    CarIcon,
    BikeIcon,
    DumbbellIcon,
    StethoscopeIcon,
    HeartPulseIcon,
    PillIcon,
    BabyIcon,
    DogIcon,
    PawPrintIcon,
    MountainIcon,
    UmbrellaIcon,
    KeyIcon,
    SunIcon,
    MoonIcon,
    CloudSunIcon,
    WineIcon,
    PizzaIcon,
    CakeIcon,
    AppleIcon,
    SaladIcon,
    TentIcon,
    AnchorIcon,
    BusIcon,
    TrainFrontIcon,
    FuelIcon,
    TractorIcon,
    WheatIcon,
    HardHatIcon,
    ConstructionIcon,
    Paintbrush2Icon,
    MicroscopeIcon,
    FlaskConicalIcon,
    TestTubeIcon,
    DnaIcon,
    SyringeIcon,
    BoneIcon,
    AirVentIcon,
    FanIcon,
    ThermometerIcon,
    SnowflakeIcon,
    PlugZapIcon,
    DropletsIcon,
    WavesIcon,
    PaintRollerIcon,
    SprayCanIcon,
    TreesIcon,
    ShovelIcon,
    FenceIcon,
    BrickWallIcon,
    DrillIcon,
    Trash2Icon,
    SlidersHorizontalIcon,
    SlidersVerticalIcon,
    ToggleLeftIcon,
    RefreshCwIcon,
    RotateCwIcon,
    DownloadIcon,
    UploadIcon,
    SaveIcon,
    ZoomInIcon,
    MaximizeIcon,
    MinimizeIcon,
    ExpandIcon,
    MoveIcon,
    GripIcon,
    InfinityIcon,
    CommandIcon,
    OptionIcon,
    PaperclipIcon,
    PinIcon,
    Grid2x2Icon,
    Columns3Icon,
    Rows3Icon,
    TableIcon,
    Table2Icon,
    Columns2Icon,
    SquareDashedIcon,
    FullscreenIcon,
    MergeIcon,
    SplitIcon,
    UngroupIcon,
    CombineIcon,
    LocateFixedIcon,
    PointerIcon,
    HandIcon,
    type LucideIcon,
} from "lucide-react";

export const SERVICE_ICON_MAP: Record<string, LucideIcon> = {
    Palette: PaletteIcon,
    Brush: BrushIcon,
    Paintbrush: PaintbrushIcon,
    PaintBucket: PaintBucketIcon,
    PenTool: PenToolIcon,
    Pencil: PencilIcon,
    PenLine: PenLineIcon,
    Shapes: ShapesIcon,
    Layers: LayersIcon,
    Layers2: Layers2Icon,
    Frame: FrameIcon,
    Crop: CropIcon,
    Scissors: ScissorsIcon,
    Pipette: PipetteIcon,
    Eraser: EraserIcon,
    Highlighter: HighlighterIcon,
    Image: ImageIcon,
    Images: ImagesIcon,
    ImagePlus: ImagePlusIcon,
    Camera: CameraIcon,
    Aperture: ApertureIcon,
    Wand: WandIcon,
    WandSparkles: WandSparklesIcon,
    Sparkles: SparklesIcon,
    Sparkle: SparkleIcon,
    Star: StarIcon,
    Gem: GemIcon,
    Crown: CrownIcon,
    Award: AwardIcon,
    Type: TypeIcon,
    Baseline: BaselineIcon,
    LetterText: LetterTextIcon,
    SwatchBook: SwatchBookIcon,
    Component: ComponentIcon,
    Grid3x3: Grid3x3Icon,
    LayoutGrid: LayoutGridIcon,
    LayoutTemplate: LayoutTemplateIcon,
    LayoutDashboard: LayoutDashboardIcon,
    LayoutList: LayoutListIcon,
    Layout: LayoutIcon,
    PanelTop: PanelTopIcon,
    Ruler: RulerIcon,
    DraftingCompass: DraftingCompassIcon,
    Spline: SplineIcon,
    Blend: BlendIcon,
    Contrast: ContrastIcon,
    Droplet: DropletIcon,
    Stamp: StampIcon,
    Sticker: StickerIcon,
    BadgeCheck: BadgeCheckIcon,
    Feather: FeatherIcon,
    Signature: SignatureIcon,
    Square: SquareIcon,
    Circle: CircleIcon,
    Triangle: TriangleIcon,
    Hexagon: HexagonIcon,
    Diamond: DiamondIcon,
    Pentagon: PentagonIcon,
    Octagon: OctagonIcon,
    Shell: ShellIcon,
    Flower: FlowerIcon,
    Flower2: Flower2Icon,
    Rainbow: RainbowIcon,
    Code: CodeIcon,
    CodeXml: CodeXmlIcon,
    Braces: BracesIcon,
    Brackets: BracketsIcon,
    Terminal: TerminalIcon,
    SquareTerminal: SquareTerminalIcon,
    Globe: GlobeIcon,
    Earth: EarthIcon,
    Monitor: MonitorIcon,
    MonitorSmartphone: MonitorSmartphoneIcon,
    Laptop: LaptopIcon,
    Smartphone: SmartphoneIcon,
    Tablet: TabletIcon,
    TabletSmartphone: TabletSmartphoneIcon,
    AppWindow: AppWindowIcon,
    Server: ServerIcon,
    Database: DatabaseIcon,
    Cloud: CloudIcon,
    CloudUpload: CloudUploadIcon,
    CloudCog: CloudCogIcon,
    Cpu: CpuIcon,
    HardDrive: HardDriveIcon,
    Network: NetworkIcon,
    Wifi: WifiIcon,
    Link: LinkIcon,
    Link2: Link2Icon,
    Plug: PlugIcon,
    Puzzle: PuzzleIcon,
    Bug: BugIcon,
    GitBranch: GitBranchIcon,
    GitMerge: GitMergeIcon,
    GitPullRequest: GitPullRequestIcon,
    Webhook: WebhookIcon,
    Workflow: WorkflowIcon,
    Blocks: BlocksIcon,
    Boxes: BoxesIcon,
    Settings: SettingsIcon,
    Settings2: Settings2Icon,
    Wrench: WrenchIcon,
    Hammer: HammerIcon,
    Cog: CogIcon,
    Rocket: RocketIcon,
    Zap: ZapIcon,
    Gauge: GaugeIcon,
    ShieldCheck: ShieldCheckIcon,
    Shield: ShieldIcon,
    Lock: LockIcon,
    KeyRound: KeyRoundIcon,
    Fingerprint: FingerprintIcon,
    Accessibility: AccessibilityIcon,
    MousePointer: MousePointerIcon,
    MousePointerClick: MousePointerClickIcon,
    Keyboard: KeyboardIcon,
    FileCode: FileCodeIcon,
    FileJson: FileJsonIcon,
    Container: ContainerIcon,
    Binary: BinaryIcon,
    Bot: BotIcon,
    BrainCircuit: BrainCircuitIcon,
    Brain: BrainIcon,
    Cable: CableIcon,
    Router: RouterIcon,
    Unplug: UnplugIcon,
    Satellite: SatelliteIcon,
    Radio: RadioIcon,
    QrCode: QrCodeIcon,
    ScanLine: ScanLineIcon,
    Microchip: MicrochipIcon,
    Variable: VariableIcon,
    FunctionSquare: FunctionSquareIcon,
    Sigma: SigmaIcon,
    ShoppingBag: ShoppingBagIcon,
    ShoppingCart: ShoppingCartIcon,
    ShoppingBasket: ShoppingBasketIcon,
    Store: StoreIcon,
    Package: PackageIcon,
    PackageSearch: PackageSearchIcon,
    PackageCheck: PackageCheckIcon,
    PackageOpen: PackageOpenIcon,
    PackagePlus: PackagePlusIcon,
    Truck: TruckIcon,
    Tag: TagIcon,
    Tags: TagsIcon,
    Ticket: TicketIcon,
    Receipt: ReceiptIcon,
    ReceiptText: ReceiptTextIcon,
    CreditCard: CreditCardIcon,
    Wallet: WalletIcon,
    Banknote: BanknoteIcon,
    Coins: CoinsIcon,
    DollarSign: DollarSignIcon,
    Euro: EuroIcon,
    PoundSterling: PoundSterlingIcon,
    BadgePercent: BadgePercentIcon,
    Percent: PercentIcon,
    Gift: GiftIcon,
    Barcode: BarcodeIcon,
    ScanBarcode: ScanBarcodeIcon,
    Warehouse: WarehouseIcon,
    Handshake: HandshakeIcon,
    HandCoins: HandCoinsIcon,
    PiggyBank: PiggyBankIcon,
    Calculator: CalculatorIcon,
    Scale: ScaleIcon,
    Forklift: ForkliftIcon,
    Plane: PlaneIcon,
    Ship: ShipIcon,
    MapPin: MapPinIcon,
    Map: MapIcon,
    Shirt: ShirtIcon,
    Watch: WatchIcon,
    Glasses: GlassesIcon,
    Footprints: FootprintsIcon,
    Sofa: SofaIcon,
    Lamp: LampIcon,
    Armchair: ArmchairIcon,
    Bed: BedIcon,
    Megaphone: MegaphoneIcon,
    TrendingUp: TrendingUpIcon,
    ChartLine: ChartLineIcon,
    ChartBar: ChartBarIcon,
    ChartPie: ChartPieIcon,
    ChartColumn: ChartColumnIcon,
    ChartArea: ChartAreaIcon,
    ChartNoAxesCombined: ChartNoAxesCombinedIcon,
    ChartSpline: ChartSplineIcon,
    Presentation: PresentationIcon,
    Target: TargetIcon,
    Crosshair: CrosshairIcon,
    Search: SearchIcon,
    SearchCheck: SearchCheckIcon,
    ScanSearch: ScanSearchIcon,
    Radar: RadarIcon,
    Rss: RssIcon,
    Mail: MailIcon,
    MailOpen: MailOpenIcon,
    Send: SendIcon,
    AtSign: AtSignIcon,
    Share: ShareIcon,
    Share2: Share2Icon,
    ThumbsUp: ThumbsUpIcon,
    Heart: HeartIcon,
    MessageCircle: MessageCircleIcon,
    MessageSquare: MessageSquareIcon,
    MessagesSquare: MessagesSquareIcon,
    Bell: BellIcon,
    BellRing: BellRingIcon,
    Speaker: SpeakerIcon,
    Podcast: PodcastIcon,
    Newspaper: NewspaperIcon,
    Hash: HashIcon,
    Flame: FlameIcon,
    Magnet: MagnetIcon,
    Funnel: FunnelIcon,
    Eye: EyeIcon,
    Lightbulb: LightbulbIcon,
    Goal: GoalIcon,
    Trophy: TrophyIcon,
    Medal: MedalIcon,
    Flag: FlagIcon,
    Milestone: MilestoneIcon,
    Signpost: SignpostIcon,
    Compass: CompassIcon,
    Navigation: NavigationIcon,
    Activity: ActivityIcon,
    MousePointer2: MousePointer2Icon,
    Smile: SmileIcon,
    Users2: Users2Icon,
    UserSearch: UserSearchIcon,
    Telescope: TelescopeIcon,
    Binoculars: BinocularsIcon,
    Video: VideoIcon,
    Film: FilmIcon,
    Clapperboard: ClapperboardIcon,
    Play: PlayIcon,
    CirclePlay: CirclePlayIcon,
    MonitorPlay: MonitorPlayIcon,
    Tv: TvIcon,
    Projector: ProjectorIcon,
    Focus: FocusIcon,
    Scan: ScanIcon,
    Move3d: Move3dIcon,
    Rotate3d: Rotate3dIcon,
    Box: BoxIcon,
    Cylinder: CylinderIcon,
    Cone: ConeIcon,
    Pyramid: PyramidIcon,
    Torus: TorusIcon,
    Orbit: OrbitIcon,
    Atom: AtomIcon,
    Axis3d: Axis3dIcon,
    Music: MusicIcon,
    Music2: Music2Icon,
    Mic: MicIcon,
    MicVocal: MicVocalIcon,
    Headphones: HeadphonesIcon,
    AudioLines: AudioLinesIcon,
    AudioWaveform: AudioWaveformIcon,
    Volume2: Volume2Icon,
    Disc: DiscIcon,
    Disc3: Disc3Icon,
    Drama: DramaIcon,
    Ghost: GhostIcon,
    Gamepad2: Gamepad2Icon,
    Joystick: JoystickIcon,
    Popcorn: PopcornIcon,
    SquarePlay: SquarePlayIcon,
    Timer: TimerIcon,
    Repeat: RepeatIcon,
    Shuffle: ShuffleIcon,
    FastForward: FastForwardIcon,
    Rewind: RewindIcon,
    SkipForward: SkipForwardIcon,
    Webcam: WebcamIcon,
    Cctv: CctvIcon,
    SwitchCamera: SwitchCameraIcon,
    ImagePlay: ImagePlayIcon,
    Spotlight: SpotlightIcon,
    FileText: FileTextIcon,
    File: FileIcon,
    Files: FilesIcon,
    FilePen: FilePenIcon,
    FileCheck: FileCheckIcon,
    FileSearch: FileSearchIcon,
    Book: BookIcon,
    BookOpen: BookOpenIcon,
    BookOpenText: BookOpenTextIcon,
    Library: LibraryIcon,
    Notebook: NotebookIcon,
    NotebookPen: NotebookPenIcon,
    NotepadText: NotepadTextIcon,
    ScrollText: ScrollTextIcon,
    Scroll: ScrollIcon,
    Quote: QuoteIcon,
    SquarePen: SquarePenIcon,
    Languages: LanguagesIcon,
    Text: TextIcon,
    Heading: HeadingIcon,
    List: ListIcon,
    ListChecks: ListChecksIcon,
    ListOrdered: ListOrderedIcon,
    ClipboardList: ClipboardListIcon,
    ClipboardCheck: ClipboardCheckIcon,
    StickyNote: StickyNoteIcon,
    Bookmark: BookmarkIcon,
    Archive: ArchiveIcon,
    FolderOpen: FolderOpenIcon,
    Folder: FolderIcon,
    Printer: PrinterIcon,
    Mails: MailsIcon,
    Inbox: InboxIcon,
    BookMarked: BookMarkedIcon,
    BookText: BookTextIcon,
    Captions: CaptionsIcon,
    Tablets: TabletsIcon,
    Briefcase: BriefcaseIcon,
    BriefcaseBusiness: BriefcaseBusinessIcon,
    Building: BuildingIcon,
    Building2: Building2Icon,
    Landmark: LandmarkIcon,
    Factory: FactoryIcon,
    Users: UsersIcon,
    User: UserIcon,
    UserCheck: UserCheckIcon,
    UserPlus: UserPlusIcon,
    UserCog: UserCogIcon,
    UserRound: UserRoundIcon,
    Contact: ContactIcon,
    IdCard: IdCardIcon,
    HeartHandshake: HeartHandshakeIcon,
    Laugh: LaughIcon,
    Calendar: CalendarIcon,
    CalendarCheck: CalendarCheckIcon,
    CalendarDays: CalendarDaysIcon,
    Clock: ClockIcon,
    Hourglass: HourglassIcon,
    AlarmClock: AlarmClockIcon,
    Headset: HeadsetIcon,
    Phone: PhoneIcon,
    PhoneCall: PhoneCallIcon,
    LifeBuoy: LifeBuoyIcon,
    CircleHelp: CircleHelpIcon,
    Info: InfoIcon,
    MessageCircleQuestion: MessageCircleQuestionIcon,
    ShieldPlus: ShieldPlusIcon,
    Gavel: GavelIcon,
    GraduationCap: GraduationCapIcon,
    School: SchoolIcon,
    Kanban: KanbanIcon,
    SquareKanban: SquareKanbanIcon,
    ListTodo: ListTodoIcon,
    CheckCheck: CheckCheckIcon,
    CircleCheck: CircleCheckIcon,
    Group: GroupIcon,
    Waypoints: WaypointsIcon,
    Leaf: LeafIcon,
    Sprout: SproutIcon,
    TreePine: TreePineIcon,
    Recycle: RecycleIcon,
    House: HouseIcon,
    Hotel: HotelIcon,
    Utensils: UtensilsIcon,
    Coffee: CoffeeIcon,
    Car: CarIcon,
    Bike: BikeIcon,
    Dumbbell: DumbbellIcon,
    Stethoscope: StethoscopeIcon,
    HeartPulse: HeartPulseIcon,
    Pill: PillIcon,
    Baby: BabyIcon,
    Dog: DogIcon,
    PawPrint: PawPrintIcon,
    Mountain: MountainIcon,
    Umbrella: UmbrellaIcon,
    Key: KeyIcon,
    Sun: SunIcon,
    Moon: MoonIcon,
    CloudSun: CloudSunIcon,
    Wine: WineIcon,
    Pizza: PizzaIcon,
    Cake: CakeIcon,
    Apple: AppleIcon,
    Salad: SaladIcon,
    Tent: TentIcon,
    Anchor: AnchorIcon,
    Bus: BusIcon,
    TrainFront: TrainFrontIcon,
    Fuel: FuelIcon,
    Tractor: TractorIcon,
    Wheat: WheatIcon,
    HardHat: HardHatIcon,
    Construction: ConstructionIcon,
    Paintbrush2: Paintbrush2Icon,
    Microscope: MicroscopeIcon,
    FlaskConical: FlaskConicalIcon,
    TestTube: TestTubeIcon,
    Dna: DnaIcon,
    Syringe: SyringeIcon,
    Bone: BoneIcon,
    AirVent: AirVentIcon,
    Fan: FanIcon,
    Thermometer: ThermometerIcon,
    Snowflake: SnowflakeIcon,
    PlugZap: PlugZapIcon,
    Droplets: DropletsIcon,
    Waves: WavesIcon,
    PaintRoller: PaintRollerIcon,
    SprayCan: SprayCanIcon,
    Trees: TreesIcon,
    Shovel: ShovelIcon,
    Fence: FenceIcon,
    BrickWall: BrickWallIcon,
    Drill: DrillIcon,
    Trash2: Trash2Icon,
    SlidersHorizontal: SlidersHorizontalIcon,
    SlidersVertical: SlidersVerticalIcon,
    ToggleLeft: ToggleLeftIcon,
    RefreshCw: RefreshCwIcon,
    RotateCw: RotateCwIcon,
    Download: DownloadIcon,
    Upload: UploadIcon,
    Save: SaveIcon,
    ZoomIn: ZoomInIcon,
    Maximize: MaximizeIcon,
    Minimize: MinimizeIcon,
    Expand: ExpandIcon,
    Move: MoveIcon,
    Grip: GripIcon,
    Infinity: InfinityIcon,
    Command: CommandIcon,
    Option: OptionIcon,
    Paperclip: PaperclipIcon,
    Pin: PinIcon,
    Grid2x2: Grid2x2Icon,
    Columns3: Columns3Icon,
    Rows3: Rows3Icon,
    Table: TableIcon,
    Table2: Table2Icon,
    Columns2: Columns2Icon,
    SquareDashed: SquareDashedIcon,
    Fullscreen: FullscreenIcon,
    Merge: MergeIcon,
    Split: SplitIcon,
    Ungroup: UngroupIcon,
    Combine: CombineIcon,
    LocateFixed: LocateFixedIcon,
    Pointer: PointerIcon,
    Hand: HandIcon,
};

export const SERVICE_ICON_CATEGORIES: {
    id: string;
    label: string;
    icons: string[];
}[] = [
    {
        id: "design",
        label: "Design & Branding",
        icons: [
            "Palette",
            "Brush",
            "Paintbrush",
            "PaintBucket",
            "PenTool",
            "Pencil",
            "PenLine",
            "Shapes",
            "Layers",
            "Layers2",
            "Frame",
            "Crop",
            "Scissors",
            "Pipette",
            "Eraser",
            "Highlighter",
            "Image",
            "Images",
            "ImagePlus",
            "Camera",
            "Aperture",
            "Wand",
            "WandSparkles",
            "Sparkles",
            "Sparkle",
            "Star",
            "Gem",
            "Crown",
            "Award",
            "Type",
            "Baseline",
            "LetterText",
            "SwatchBook",
            "Component",
            "Grid3x3",
            "LayoutGrid",
            "LayoutTemplate",
            "LayoutDashboard",
            "LayoutList",
            "Layout",
            "PanelTop",
            "Ruler",
            "DraftingCompass",
            "Spline",
            "Blend",
            "Contrast",
            "Droplet",
            "Stamp",
            "Sticker",
            "BadgeCheck",
            "Feather",
            "Signature",
            "Square",
            "Circle",
            "Triangle",
            "Hexagon",
            "Diamond",
            "Pentagon",
            "Octagon",
            "Shell",
            "Flower",
            "Flower2",
            "Rainbow",
        ],
    },
    {
        id: "web",
        label: "Web & Development",
        icons: [
            "Code",
            "CodeXml",
            "Braces",
            "Brackets",
            "Terminal",
            "SquareTerminal",
            "Globe",
            "Earth",
            "Monitor",
            "MonitorSmartphone",
            "Laptop",
            "Smartphone",
            "Tablet",
            "TabletSmartphone",
            "AppWindow",
            "Server",
            "Database",
            "Cloud",
            "CloudUpload",
            "CloudCog",
            "Cpu",
            "HardDrive",
            "Network",
            "Wifi",
            "Link",
            "Link2",
            "Plug",
            "Puzzle",
            "Bug",
            "GitBranch",
            "GitMerge",
            "GitPullRequest",
            "Webhook",
            "Workflow",
            "Blocks",
            "Boxes",
            "Settings",
            "Settings2",
            "Wrench",
            "Hammer",
            "Cog",
            "Rocket",
            "Zap",
            "Gauge",
            "ShieldCheck",
            "Shield",
            "Lock",
            "KeyRound",
            "Fingerprint",
            "Accessibility",
            "MousePointer",
            "MousePointerClick",
            "Keyboard",
            "FileCode",
            "FileJson",
            "Container",
            "Binary",
            "Bot",
            "BrainCircuit",
            "Brain",
            "Cable",
            "Router",
            "Unplug",
            "Satellite",
            "Radio",
            "QrCode",
            "ScanLine",
            "Microchip",
            "Variable",
            "FunctionSquare",
            "Sigma",
        ],
    },
    {
        id: "ecommerce",
        label: "E-commerce & Sales",
        icons: [
            "ShoppingBag",
            "ShoppingCart",
            "ShoppingBasket",
            "Store",
            "Package",
            "PackageSearch",
            "PackageCheck",
            "PackageOpen",
            "PackagePlus",
            "Truck",
            "Tag",
            "Tags",
            "Ticket",
            "Receipt",
            "ReceiptText",
            "CreditCard",
            "Wallet",
            "Banknote",
            "Coins",
            "DollarSign",
            "Euro",
            "PoundSterling",
            "BadgePercent",
            "Percent",
            "Gift",
            "Barcode",
            "ScanBarcode",
            "Warehouse",
            "Handshake",
            "HandCoins",
            "PiggyBank",
            "Calculator",
            "Scale",
            "Forklift",
            "Plane",
            "Ship",
            "MapPin",
            "Map",
            "Shirt",
            "Watch",
            "Glasses",
            "Footprints",
            "Sofa",
            "Lamp",
            "Armchair",
            "Bed",
        ],
    },
    {
        id: "marketing",
        label: "Marketing & Growth",
        icons: [
            "Megaphone",
            "TrendingUp",
            "ChartLine",
            "ChartBar",
            "ChartPie",
            "ChartColumn",
            "ChartArea",
            "ChartNoAxesCombined",
            "ChartSpline",
            "Presentation",
            "Target",
            "Crosshair",
            "Search",
            "SearchCheck",
            "ScanSearch",
            "Radar",
            "Rss",
            "Mail",
            "MailOpen",
            "Send",
            "AtSign",
            "Share",
            "Share2",
            "ThumbsUp",
            "Heart",
            "MessageCircle",
            "MessageSquare",
            "MessagesSquare",
            "Bell",
            "BellRing",
            "Speaker",
            "Podcast",
            "Newspaper",
            "Hash",
            "Flame",
            "Magnet",
            "Funnel",
            "Eye",
            "Lightbulb",
            "Goal",
            "Trophy",
            "Medal",
            "Flag",
            "Milestone",
            "Signpost",
            "Compass",
            "Navigation",
            "Activity",
            "MousePointer2",
            "Smile",
            "Users2",
            "UserSearch",
            "Telescope",
            "Binoculars",
        ],
    },
    {
        id: "video",
        label: "Video & Animation",
        icons: [
            "Video",
            "Film",
            "Clapperboard",
            "Play",
            "CirclePlay",
            "MonitorPlay",
            "Tv",
            "Projector",
            "Focus",
            "Scan",
            "Move3d",
            "Rotate3d",
            "Box",
            "Cylinder",
            "Cone",
            "Pyramid",
            "Torus",
            "Orbit",
            "Atom",
            "Axis3d",
            "Music",
            "Music2",
            "Mic",
            "MicVocal",
            "Headphones",
            "AudioLines",
            "AudioWaveform",
            "Volume2",
            "Disc",
            "Disc3",
            "Drama",
            "Ghost",
            "Gamepad2",
            "Joystick",
            "Popcorn",
            "SquarePlay",
            "Timer",
            "Repeat",
            "Shuffle",
            "FastForward",
            "Rewind",
            "SkipForward",
            "Webcam",
            "Cctv",
            "SwitchCamera",
            "ImagePlay",
            "Spotlight",
        ],
    },
    {
        id: "content",
        label: "Content & Writing",
        icons: [
            "FileText",
            "File",
            "Files",
            "FilePen",
            "FileCheck",
            "FileSearch",
            "Book",
            "BookOpen",
            "BookOpenText",
            "Library",
            "Notebook",
            "NotebookPen",
            "NotepadText",
            "ScrollText",
            "Scroll",
            "Quote",
            "SquarePen",
            "Languages",
            "Text",
            "Heading",
            "List",
            "ListChecks",
            "ListOrdered",
            "ClipboardList",
            "ClipboardCheck",
            "StickyNote",
            "Bookmark",
            "Archive",
            "FolderOpen",
            "Folder",
            "Printer",
            "Mails",
            "Inbox",
            "BookMarked",
            "BookText",
            "Captions",
            "Tablets",
        ],
    },
    {
        id: "business",
        label: "Business & Team",
        icons: [
            "Briefcase",
            "BriefcaseBusiness",
            "Building",
            "Building2",
            "Landmark",
            "Factory",
            "Users",
            "User",
            "UserCheck",
            "UserPlus",
            "UserCog",
            "UserRound",
            "Contact",
            "IdCard",
            "HeartHandshake",
            "Laugh",
            "Calendar",
            "CalendarCheck",
            "CalendarDays",
            "Clock",
            "Hourglass",
            "AlarmClock",
            "Headset",
            "Phone",
            "PhoneCall",
            "LifeBuoy",
            "CircleHelp",
            "Info",
            "MessageCircleQuestion",
            "ShieldPlus",
            "Gavel",
            "GraduationCap",
            "School",
            "Kanban",
            "SquareKanban",
            "ListTodo",
            "CheckCheck",
            "CircleCheck",
            "Group",
            "Waypoints",
        ],
    },
    {
        id: "industry",
        label: "Industries & Lifestyle",
        icons: [
            "Leaf",
            "Sprout",
            "TreePine",
            "Recycle",
            "House",
            "Hotel",
            "Utensils",
            "Coffee",
            "Car",
            "Bike",
            "Dumbbell",
            "Stethoscope",
            "HeartPulse",
            "Pill",
            "Baby",
            "Dog",
            "PawPrint",
            "Mountain",
            "Umbrella",
            "Key",
            "Sun",
            "Moon",
            "CloudSun",
            "Wine",
            "Pizza",
            "Cake",
            "Apple",
            "Salad",
            "Tent",
            "Anchor",
            "Bus",
            "TrainFront",
            "Fuel",
            "Tractor",
            "Wheat",
            "HardHat",
            "Construction",
            "Paintbrush2",
            "Microscope",
            "FlaskConical",
            "TestTube",
            "Dna",
            "Syringe",
            "Bone",
            "AirVent",
            "Fan",
            "Thermometer",
            "Snowflake",
            "PlugZap",
            "Droplets",
            "Waves",
            "PaintRoller",
            "SprayCan",
            "Trees",
            "Shovel",
            "Fence",
            "BrickWall",
            "Drill",
            "Trash2",
        ],
    },
    {
        id: "tools",
        label: "Tools & Interface",
        icons: [
            "SlidersHorizontal",
            "SlidersVertical",
            "ToggleLeft",
            "RefreshCw",
            "RotateCw",
            "Download",
            "Upload",
            "Save",
            "ZoomIn",
            "Maximize",
            "Minimize",
            "Expand",
            "Move",
            "Grip",
            "Infinity",
            "Command",
            "Option",
            "Paperclip",
            "Pin",
            "Grid2x2",
            "Columns3",
            "Rows3",
            "Table",
            "Table2",
            "Columns2",
            "SquareDashed",
            "Fullscreen",
            "Merge",
            "Split",
            "Ungroup",
            "Combine",
            "LocateFixed",
            "Pointer",
            "Hand",
        ],
    },
];
